import os
import json
import glob
from datetime import datetime
from rich.console import Console

console = Console()

def generate_html_report(target):
    console.print(f"\n[bold blue][▶] Generating Professional HTML Report for {target}...[/bold blue]")
    
    report_dir = "reports"
    if not os.path.exists(report_dir):
        console.print("[red][!] No reports directory found.[/red]")
        return

    # Find relevant files
    subdomain_files = glob.glob(f"{report_dir}/{target}_*subdomains.txt")
    port_files = glob.glob(f"{report_dir}/{target}_*ports.txt")
    vuln_files = glob.glob(f"{report_dir}/{target}_*vulns.json")

    subdomains = []
    ports = []
    vulns = []

    if subdomain_files:
        with open(subdomain_files[0], 'r') as f:
            subdomains = f.read().splitlines()
            
    if port_files:
        with open(port_files[0], 'r') as f:
            for line in f:
                parts = line.strip().split('\t')
                if len(parts) >= 2:
                    ports.append({"port": parts[0], "service": parts[1], "version": parts[2] if len(parts) > 2 else ""})

    if vuln_files:
        with open(vuln_files[0], 'r') as f:
            vulns = json.load(f)

    # Generate HTML (Dark Theme)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Limit subdomains to top 50 for clean report
    sub_rows = ''.join([f"<tr><td>{i+1}</td><td>{sub}</td></tr>" for i, sub in enumerate(subdomains[:50])])
    if len(subdomains) > 50:
        sub_rows += f"<tr><td colspan='2'>... and {len(subdomains)-50} more</td></tr>"
        
    port_rows = ''.join([f"<tr><td>{p['port']}</td><td>{p['service']}</td><td>{p['version']}</td></tr>" for p in ports])
    
    vuln_rows = ''.join([f"<tr><td class='severity-{v['severity'].lower()}'>{v['severity']}</td><td>{v['name']}</td><td>{v['template']}</td></tr>" for v in vulns])

    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>VulnSpecter Report: {target}</title>
        <style>
            body {{ font-family: 'Segoe UI', sans-serif; background-color: #1e1e1e; color: #d4d4d4; margin: 0; padding: 20px; }}
            .container {{ max-width: 1000px; margin: 0 auto; background-color: #252526; padding: 30px; border-radius: 8px; }}
            h1 {{ color: #007acc; border-bottom: 2px solid #007acc; padding-bottom: 10px; }}
            h2 {{ color: #ce9178; margin-top: 30px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 15px; background-color: #1e1e1e; }}
            th, td {{ border: 1px solid #3e3e42; padding: 12px; text-align: left; }}
            th {{ background-color: #2d2d30; color: #569cd6; }}
            .severity-critical {{ color: #f44336; font-weight: bold; }}
            .severity-high {{ color: #ff9800; font-weight: bold; }}
            .severity-medium {{ color: #ffeb3b; }}
            .severity-low {{ color: #4caf50; }}
            .footer {{ margin-top: 40px; text-align: center; color: #858585; font-size: 0.9em; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>VulnSpecter Security Report</h1>
            <p><strong>Target:</strong> {target} | <strong>Generated:</strong> {timestamp}</p>
            <p><strong>Codename:</strong> Vuln5p3c73r Edition</p>

            <h2>1. Subdomain Enumeration ({len(subdomains)} found)</h2>
            <table><tr><th>#</th><th>Subdomain</th></tr>{sub_rows}</table>

            <h2>2. Open Ports & Services ({len(ports)} found)</h2>
            <table><tr><th>Port</th><th>Service</th><th>Version</th></tr>{port_rows}</table>

            <h2>3. Vulnerabilities ({len(vulns)} found)</h2>
            <table><tr><th>Severity</th><th>Name</th><th>Template</th></tr>{vuln_rows}</table>

            <div class="footer"><p>Generated by VulnSpecter v1.0.0 | Automated Security Testing Platform</p></div>
        </div>
    </body>
    </html>
    """

    output_path = f"{report_dir}/{target}_final_report.html"
    with open(output_path, 'w') as f:
        f.write(html_content)
        
    console.print(f"[bold green][+] Professional HTML Report saved to: {output_path}[/bold green]")
    console.print(f"[bold blue][*] Open it in your browser to view the full report![/bold blue]\n")
